version: '3'
services:

  # Create backend container
  backend:
    # Create backend container  
    build: .
    ports:
      - "3000:3000"
    container_name: backend-docker
    restart: always
    links:
    - mongo
    depends_on:
      - mongo
   
    # Create database container
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
      
      


  