version: '3'
services:

  # Create backend container
  backend:
    # Create backend container  
    build: .
    ports:
      - "3000:3000"
    container_name: backend-docker
    restart: always
    depends_on:
      - mongo
      - es01
    networks:
      - mern-app
    # Create database container
  mongo:
    image: candis/mongo-replica-set
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

  # Create elasticsearch container
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: es01
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

    ports:
      - 9200:9200

    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  elastic-data:
    driver: local
