version: '3'
services:

  # Create backend container
  backend:
    # Create backend container  
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - elastic

    volumes:
      - .:/main
      - /main/node_modules  
 
 

  # Create elasticsearch container
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
   

    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
   

    ports:
      - 127.0.0.1:5601:5601
    
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200

    depends_on:
      - elastic

